# Generated by Django 4.2.1 on 2023-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_city_order_state_order_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='place_order',
            field=models.CharField(default='', max_length=10),
        ),
    ]
