# Generated by Django 4.2.1 on 2023-06-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_mobile_number_order_place_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tick_marked',
            field=models.CharField(default='', max_length=10),
        ),
    ]
