# Generated by Django 4.2.1 on 2023-06-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_address_order_place_order_order_tick_marked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='place_order',
        ),
    ]
